# Generated by Django 4.0 on 2022-01-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='dep',
        ),
    ]
