# Generated by Django 4.0 on 2022-01-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementApp', '0002_remove_prof_dep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rollno', models.IntegerField()),
                ('prof_name', models.CharField(max_length=20)),
                ('sub', models.CharField(max_length=20)),
                ('dep_name', models.CharField(max_length=20)),
            ],
        ),
    ]
